Roukys/HHauto

HHAuto.user.js

Revert "Calculate for leagues"

---

HHAuto.user.js

Revert "v5.1.0"

---

HHAuto.user.js

fix #47 
close #39 
resolve #38 
close #37 
fix #35 
close #24

Pop delay issue

---

HHAuto.user.js

Test server update

---

HHAuto.user.js
README.md

Add Button for open the Git repository
Line 17: CSS for the new button
Line 3931:  add the button to the UI
Line 4135: New button Event

Add Git btn

---

HHAuto.user.js

Update for the new boss "Sake" at line 7223 and line 7575

Updated names for the new boss "Sake"

---

HHAuto.user.js

Nthousand issue #241

---

HHAuto.user.js

Set fixed maxHeight and added a mouseover event listener to switch to maxHeight = "none"

Infobox over Harem button solution 3

---

HHAuto.user.js

quick fix until better solution coded
@Roukys it's quite urgent, hope you get notified soon ;)

prevent kobans spending on books and gifts

---

HHAuto.user.js

removed height and width so they get their default value "auto"

resized menu

---

HHAuto.user.js

Removed all the "Wanna buy [...] but can't."
Now only the actual buying will be logged.

Removed unwanted shopping log entries

---

HHAuto.user.js

Correcting #296 PowerCalc result misplaced

---

HHAuto.user.js

button and menu position

---

HHAuto.user.js

Fix collect Daily Goals

---

HHAuto.user.js

Fix PoP and PoV

---

HHAuto.user.js

Fix comixharem on nutaku and add troll

---

HHAuto.user.js

bugfix, updates pornstarharem and hornyheroes

---

HHAuto.user.js

#465
#266
ignore equipped items for sale
#535

Fix and rewrite MenuSell

---

HHAuto.user.js

Added a button to toggle all items in the collectable preferences box
Reorganized the layout slightly for consistency

Collectable Preferences box cleanup

---

HHAuto.user.js

I added the ability to select "PoP Precision", which tries to find an efficient grouping of girls for Places of Power instead of using the auto button.

Places of Power Precision

---

HHAuto.user.js

Interrupts the script from taking action for 5 seconds when mouse movement is
detected. A configuration toggle is placed in the global settings area of the
config screen to allow a choice of whether the feature is enabled or not.

New Feature - Mouse Pause

---

HHAuto.user.js

Fix an issue where teams resulting in very long times were valid. Added some more comments and setup timing debugging to be possible without code changes.

Pop precision

---

HHAuto.user.js

Tested only with gift and potions.

Update buying system after market update

---

HHAuto.user.js

Fix reward type detection after update
New json object:

Fix auto collect from POV/POG and seasons

---

HHAuto.user.js

Add Auga boss name in HH (Same name in FR or EN)

Add Auga boss name in HH #601

---

HHAuto.user.js

New link :
Destination on double click

Add new feature to Go to girl update page on double click from edit team #545

---

HHAuto.user.js

- Fix, detect event girls in troll reward #608 As provided by [DortenThe2nd](https://github.com/DortenThe2nd)
- Fix auto quest with energy #609 As provided by [DortenThe2nd](https://github.com/DortenThe2nd)
- Fix buy ticket with energy #606

fix issues after updates #606, #608, #609

---

HHAuto.user.js

Fix all collect rewards
(new classes to get element, and missing data-d in some cases now...)
Add new mythic type:
Create a detection to deactivate seasonal event when the event is over to prevent infinite loop.

Fix collect rewards #612 and add mythic #614

---

HHAuto.user.js

Add new boss in Pornharem #613

---

HHAuto.user.js

After update, was not collecting anymore
@Roukys

Fix collect free pachinko

---

HHAuto.user.js

Forget this function in last commit.
@Roukys

Fix collect free mythic pachinko

---

HHAuto.user.js

I'm not able to validate this as I don't have such quest right now.
If someone can validate and comment this PR, this would help.
At least the function is working:

Fix price detection in quest #627

---

HHAuto.user.js

I broke the energy amount detection.
Please @Roukys

Fix energy detection in quest #627

---

HHAuto.user.js

Use fonction https://github.com/Roukys/HHauto/blob/main/HHAuto.user.js#L129

Fix amount in quest with thousand separator #627

---

HHAuto.user.js

Add option to hide collected rewards on seasonal events #633

---

HHAuto.user.js

The checkbox will prefill the input field

Add new option to fill Pachinko input with all available orbs #623

---

HHAuto.user.js

Fix designs #623

---

HHAuto.user.js

Allow change of mouse timeout #568

---

HHAuto.user.js

All teams need to be filled before the script will start the events.
It will start with the last team first and then go to first one as soon as the team is tired.

Add new feature to perform boss bang events #467

---

HHAuto.user.js

This allow high level player to configure to only fill one team
1 will start with first team
5 will start when last team is filled and goes down to first team

Add team number to start with #543

---

HHAuto.user.js

Add space in spanish text to avoid extending menu

---

HHAuto.user.js

Add space between pachinko checkbox and make text clickable #646

---

HHAuto.user.js

Do not perform actions when no competition is active:
- collect free pachinko
- troll battles
- Season fights
- Leagues battles

Do not perform actions when no competition is active #490

---

HHAuto.user.js

Move market check first. #504
This will make the game going to home page after it.
Then on home page script will check events fixing wrong troll order #571,#653
Adding new text on time when no compet ongoing #678

Move market check first. #504

---

HHAuto.user.js

Currently only for PoV, PoG and Season.
Prepare support for seasonal event.
Fixing timer displayed doubled on home page for Pov and PoG. Add timer display for season (if not done by HH++ OCD season version)
The settings is the following:
Each event has his own activation.
Timer is common and in hour (1-99hours).
The lower the value is the higher risk exist of not collecting (Paranoia, ...)

Add new feature to collect all rewards before event finish #670

---

HHAuto.user.js

Fix a small copy paste issue in sorting opponents
Clear not used function
Add button to reach bug list #681
Add small text to warn to not use other scripts #569
The following button will not be displayed when using HH++ OCD (or BDSM)

Add new button to hide beaten opponents in leagues #569

---

HHAuto.user.js

Fix oppo stat display on the list on manual oppo selection and add points

---

HHAuto.user.js

Fix oppo stat duplicated
Fix timer status (not all wait for compet)

Fix oppo stat duplicated / Fix timer status

---

HHAuto.user.js

Make PoP higher in order, making them before troll fight. #504

Add module to count the best champion team #544

---

HHAuto.user.js

Update timer style #693

---

HHAuto.user.js

Solution is not perfect but it works.
When looking at event, script looks also for Sultry Mysteries Events.
Then on the page, it switch to shop page to refresh and switch back to grid after a few milli seconds.
#706

feat: Parse sultry Mysteries Events page and switch to shop tab to refresh it

---

HHAuto.user.js

Try to fix troll loops #711

---

HHAuto.user.js

Add new POP inverted option #709

---

HHAuto.user.js

Remove 2h limit for market update #727

Fix after update #719

---

HHAuto.user.js

Update is now based on next available time (can be 24h) And timer is update on club page if current timer is ongoing and no time available on the page (ie: champion as been reset)

Fix club champion timer #719

---

HHAuto.user.js

Update league PowerCalc location #715

---

HHAuto.user.js

Leagues self battle loop fixes

5.13.3 Leagues self battle loop

---

HHAuto.user.js

@deuxge Since we have two functions that do same conversion, did some code cleanup and verified that mythic timer is not broken

Code cleanup for duplicates

---

HHAuto.user.js

+ fix force start feature on club champion

When club champ timer is more than 30min, check every 30 min #719

---

HHAuto.user.js

Hide skip button and show challenge button in club #735

---

HHAuto.user.js

max_amount was replaced by max_regen_amount by recent game patch

Broken max_amount

---

HHAuto.user.js

and minor fixes for integrating PowerCalc inside the attack button. #715
P.S. I'm just trying to learn the GitHub platform (previously I did not deal with this site and only commented in cases of bugs), so if I did something wrong or posted it in the wrong place, I apologize in advance. 😅

Display of PowerCalc in the mobile version of League

---

HHAuto.user.js

Add new option for collecting free bundle #620 #430

---

HHAuto.user.js

Add TS troll name #752

---

HHAuto.user.js

Fix no DST offset

---

HHAuto.user.js

I currently just fix the previous algorithm.
The script will check 20 or 50 fight.
We could maybe enhance later

Fix buy for fight after update #762

---

HHAuto.user.js

There were cases where the previous calculation would get stuck in a loop or provide substandard results. This new formula should be much more robust.

Refine PoP precision calculation

---

HHAuto.user.js

Ease maintenance, enhancement
Reduce line numbers
No design update for now.
Must be identical in functionality and transparent for users.

Refactor HH auto menu creation with functions

---

HHAuto.user.js

Points limit to prevent the script performing any league fight to keep user in targetted league and avoid promotion.
Change only if you accept the risk

Allow update of league security Threshold #582

---

HHAuto.user.js

Set wait 15min when in salary amount is not reached

Avoid salary loop when min salary amount is not reached #784

---

HHAuto.user.js

Fix icons in sell menu

---

HHAuto.user.js

If enabled : POP will wait all POP are ended before starting new one.

Add param to wait all POP ended before starting new one #802

---

HHAuto.user.js

Fix leagues icons #801

---

HHAuto.user.js

Move Pop buttons to two lines #802

---

HHAuto.user.js

Drag and drop is still an action to be performed manually
Add new input to define the number of loop
The script simulate manual button/girls click. It taks a bit of time to perform.

Add feature to auto select five best girls for champion #544

---

HHAuto.user.js

Deactivate shop refresh on sultry mysteries event #811

---

HHAuto.user.js

Add Sultry Mysteries Event Refresh Shop settings #811

---

HHAuto.user.js

Add new switch for deactivation of market update #819

---

HHAuto.user.js

Add SM timer in div info and fix event parsing #811

---

HHAuto.user.js

Add option to move pInfo left #818

---

HHAuto.user.js

 Reduce left pInfo to match button without OCD script #818 

---

HHAuto.user.js

Add option to compact activities without scroll needs

---

HHAuto.user.js

Add option to add a button to reach club champion from poa objectives

---

HHAuto.user.js

Search only after start button instead of first visible one.

Refactor missions collection to be more human like #856

---

HHAuto.user.js

If enabled: keep second line matching girls when first line is not full
Add a popup like the league ones:

Add option to keep champ girls from second line if first is not full #544

---

HHAuto.user.js

Refactor event parsing functions
Add a bit of delay in reward boss bang closing to avoid being stuck

Add option to collect event chest #476

---

HHAuto.user.js

The script will save the list of girls you filtered on harem.
I RECOMMEND TO NOT DO ON FULL LIST.
If you select one action from the script menu it will use the related max out button on all the girls from the list.
If you do not manually select one, it is usually number 1. Then it will start at one until 8 and go back to harem list.
If you select girl 6, then the script will start for the 6th girl and continue until 8 and go back to harem list.
If already maxed out, the script will continue to the next one.
You can select experience or affection (one at a time).
There is no activation switch as the script will do nothing if no click on the "Give ..." menu item

Add menu option to max out girls from filtered list #688

---

HHAuto.user.js

On the girl page, you have a new action:
It will open a popup asking you the target level you want:
Then the script will use the max out button and the awake button until this level.
WARNING there is no threashold on the gems. If you have enough it will be used.

Add option to max girls #688

---

HHAuto.user.js

Add troll option to fight troll with girls

---

HHAuto.user.js

Add buy champion ticket action into scope of wait for contest

Add option to deactivate wait for contest #885

---

HHAuto.user.js

Update design of pachinko menu #887

---

HHAuto.user.js

Update free bundle after game update #891

---

HHAuto.user.js

Activate pantheon in pornstar

---

HHAuto.user.js

Add Janie Blade #938

---

HHAuto.user.js

Add new reward type #942
New option for ads / games free koban #943 #915
I have created an option to let it as before or keep the current behavior (in 5.34.15).
It doesn't look to the content so you can have other things :

Update following game update w31

---

HHAuto.user.js

Disable use of power calc with autoleague, using power from KK
Fix troll fight going to event girl when event fight is not active #937 Update contest style after OCD script update.
Go back home after get free bundle #927

League fix after game update #941

---

HHAuto.user.js

Add button for change team

---

HHAuto.user.js

Update selling equipement dialog

---

HHAuto.user.js

Add new option to stop when a girl is won in Pachinko #922

---

HHAuto.user.js

Fix collect league after game update #941

---

HHAuto.user.js
build/HHAuto.template.js
package.json
src/Module/Events/Seasonal.js
src/Service/AutoLoop.js
src/Service/ParanoiaService.js

Fixes + update seasonal event rewards display

---

HHAuto.user.js
package.json
src/Helper/StorageHelper.js
src/config/HHStoredVars.js
src/config/InputPattern.js

Stored value will be changed to 20 (To be removed in 1-2 month) If 200 is manually set, update will occurs.
During this period, max troll is 199

Change default troll by to 20 from 200 #1012

---

HHAuto.user.js
package.json
src/Module/Events/Seasonal.js
src/Module/Harem.js
src/Service/AutoLoop.js

Check for rank rewards from mega seasonal event once a day #1006

---

HHAuto.user.js
package.json
src/Helper/HHMenuHelper.js
src/Module/Champion.js
src/config/HHStoredVars.js
src/i18n/en.js

Add minimum power setting for champion team building #863

---

HHAuto.user.js
package.json
src/Helper/HHMenuHelper.js
src/Module/Booster.js
src/Module/Champion.js
src/Module/ClubChampion.js
src/Module/Events/Season.js
src/Module/League.js
src/Module/MonthlyCard.js
src/Module/Pantheon.js
src/Module/Quest.js
src/Module/Troll.js
src/Service/AutoLoop.js
src/Service/InfoService.js
src/Service/ParanoiaService.js
src/config/HHStoredVars.js
src/i18n/en.js

Refactor to align way to get energies
Check expiration time from booster

Add option to prevent season fight when no booster equipped #234

---

HHAuto.user.js
package.json
src/Module/Events/EventModule.js
src/i18n/en.js

Highlight daily mission girl in event #1023

---

HHAuto.user.js
build/HHAuto.template.js
package.json
src/Helper/RewardHelper.js
src/Module/Harem.js
src/Service/AutoLoop.js

Update girl page button position #1030

Add reward recap in POA

---

HHAuto.user.js
build/HHAuto.template.js
package.json
src/Helper/HHMenuHelper.js
src/Module/Booster.js
src/Module/Harem.js
src/Module/Pantheon.js
src/Module/TeamModule.js
src/Service/InfoService.js
src/config/HHStoredVars.js
src/i18n/en.js

Don't fight in Pantheon without boosters #1032
Refactor auto team using reset button #1029
Update go to girl page button #1030

Some updates

---

HHAuto.user.js
package.json
src/Helper/TimeHelper.js
src/Module/Champion.js
src/Module/ClubChampion.js
src/Module/Pachinko.js
src/Service/AutoLoop.js
src/Service/InfoService.js
src/Service/ParanoiaService.js
src/model/Champion.js
src/model/index.js

Update great pachinko selector
Fix event refresh too often

Update champion timer management #1046

---

HHAuto.user.js
package.json
src/Module/Events/Season.js
src/Service/AutoLoop.js

Switch order of pachinko to match game

Go back to previous season timer

---

HHAuto.user.js
package.json
src/Module/League.js
src/Module/Shop.js

Enhance compatibility with HH OCD #1066
Add random delay when selling #1046

Enhance compatibility with HH OCD #1066

---

HHAuto.user.js
package.json
src/Helper/RewardHelper.js
src/Helper/TimeHelper.js
src/Helper/TimerHelper.js
src/Module/Bundles.js
src/Module/ClubChampion.js
src/Module/Contest.js
src/Module/DailyGoals.js
src/Module/Events/PathOfGlory.js
src/Module/Events/PathOfValue.js
src/Module/Events/Season.js
src/Module/Events/Seasonal.js
src/Module/League.js

Make Timezone system back with fixed location #1072
Collect random girls shards #1067

Updates Timezone and random girls shards

---

HHAuto.user.js
package.json
src/Helper/StorageHelper.js
src/Module/HaremSalary.js
src/Service/AutoLoop.js
src/config/InputPattern.js

Remove temp reducing value from troll #1012
Small update on harem and remove from continuous action #1070

Updates troll 200 and harem

---

HHAuto.user.js
package.json
src/Module/harem/HaremGirl.js
src/i18n/en.js

Update girl message add add upgrade button from girl menu #688

---

HHAuto.user.js
package.json
src/Helper/HHMenuHelper.js
src/Module/League.js
src/config/HHStoredVars.js
src/i18n/en.js

Add option to do one league fight at a time #1087

---

HHAuto.user.js
package.json
src/config/HHEnvVariables.js

Add Gross troll

---

HHAuto.user.js
package.json
src/Module/Bundles.js
src/config/HHEnvVariables.js

+ delay when no buntton found #1102

Add POP in TPH #1100

---

HHAuto.user.js
build/HHAuto.template.js
package.json
src/Module/ClubChampion.js
src/Module/League.js
src/Module/Quest.js
src/config/HHEnvVariables.js

Fix a bug in league
Fix timer bug in club champion when limit is reached Close level up popup in quest

Add Gay pornstar support #1119

---

HHAuto.user.js
package.json
src/Module/Events/DoublePenetration.js
src/Service/AutoLoop.js

Add Go to club champion in DB

---

HHAuto.user.js
package.json
src/Module/Harem.ts
src/Module/harem/HaremGirl.ts
src/Service/StartService.ts
src/config/HHStoredVars.ts
src/config/InputPattern.ts

Fix upgrade girls stopped by other actions #1111
Fix issue when changing info popup settings
Fix input validation for boosters
Add reset season timer when changing auto season settings

Small fixes

---

HHAuto.user.js
package.json
src/Module/Troll.ts
src/Service/StartService.ts

Fix girl troll array when new troll is added

Avoid loop when not logged in #1134

---

HHAuto.user.js
build/HHAuto.template.js
package.json
src/Module/Champion.ts
src/Module/Harem.ts

Add CSS rule to show next poses #1157

Fix champion force start #1158

---

HHAuto.user.js
package.json
src/Module/Booster.ts
src/Module/Troll.ts
src/Service/AutoLoop.ts
src/config/HHStoredVars.ts

And go to shop page to force update before selecting new booster
Clear paranoia settings when toggle switch

Fix mythic troll fight not working #1165

---

HHAuto.user.js
package.json
spec/Module/Champion.spec.ts
spec/Module/ClubChampion.spec.ts
src/Helper/RewardHelper.ts
src/Module/Champion.ts
src/Module/ClubChampion.ts
src/Module/Events/Seasonal.ts
src/Module/Labyrinth.ts
src/Service/AutoLoop.ts
src/config/HHStoredVars.ts
src/i18n/en.ts

Fix small bug in labyrinth when completed.
Fix bug in align champion timers

Add collect all button in Seasonal events #1152

---

HHAuto.user.js
package.json
src/Module/Shop.ts
src/Module/Troll.ts
src/Service/StartService.ts
src/config/HHEnvVariables.ts

Fix bug when no more girls is available from a troll and selection is last or first troll with girls
Fix shop sell with more than 100 not sellable items #1184

Add Labyrinth resource in collectible element

---

HHAuto.user.js
package.json
src/Module/Events/EventModule.ts
src/Module/Harem.ts
src/Module/Labyrinth.ts
src/Module/Troll.ts
src/Module/harem/HaremGirl.ts
src/Service/AutoLoop.ts
src/Service/PageNavigationService.ts
src/config/HHEnvVariables.ts

Move DL girls stat from harem to edit teams
Update girl list from edit team
Go to edit team when needed for troll definition
Update labyrinth display

Fix some harem related functions after updates #1186

---

HHAuto.user.js
package.json
src/Module/Harem.ts
src/Module/HaremSalary.ts
src/Service/AutoLoop.ts
src/config/HHEnvVariables.ts

Fix harem collection for the first page #1188 #1191 #1186

---

HHAuto.user.js
package.json
src/Module/Events/DoublePenetration.ts
src/Module/Events/EventModule.ts
src/Module/Events/PathOfAttraction.ts
src/Service/AutoLoop.ts

Add DP collect all

---

HHAuto.user.js
build/HHAuto.template.js
package.json
src/Helper/RewardHelper.ts
src/Module/Events/DoublePenetration.ts
src/Module/Events/PathOfAttraction.ts
src/Module/Events/Season.ts
src/Module/Events/Seasonal.ts
src/Service/AutoLoop.ts

Add rewards recap on DP events

---

HHAuto.user.js
package.json
src/Helper/HHMenuHelper.ts
src/Module/Events/EventModule.ts
src/Module/HaremSalary.ts
src/Service/AutoLoop.ts
src/config/HHStoredVars.ts
src/i18n/en.ts

Add option to hide owned girls in event with many girls

---

HHAuto.user.js
build/HHAuto.template.js
package.json
src/Helper/HHMenuHelper.ts
src/Module/HaremSalary.ts
src/Module/PlaceOfPower.ts
src/Service/AutoLoop.ts
src/config/HHStoredVars.ts
src/i18n/en.ts

+ update timer from home page (if reset filter active)
+ some fixes

Add new option to reset girl filter before collecting salary #1209

---

HHAuto.user.js
build/HHAuto.template.js
package.json
src/Helper/TimeHelper.ts
src/Module/Contest.ts
src/Service/InfoService.ts
src/Service/StartService.ts

Some fix for the info div in left mode

Add safe contest time into next contest timer #1268

---

HHAuto.user.js
package.json
src/Service/AutoLoop.ts
src/Service/InfoService.ts
src/config/game/MangaRpgVars.ts

Fix ads to back #1271

---

HHAuto.user.js
package.json
src/Module/harem/Harem.ts
src/config/game/MangaRpgVars.ts

Add nutaku mangar rpg #1289

---

HHAuto.user.js
package.json
src/Module/PlaceOfPower.ts
src/Module/harem/Harem.ts
src/Service/AdsService.ts
src/config/game/GayPornstarHaremVars.ts
src/config/game/TransPornstarHaremVars.ts

limit pop when less than 10 girl

Add club section in gpsh and psh #1312

---

HHAuto.user.js
build/HHAuto.template.js
package.json
src/Module/PlaceOfPower.ts
src/Module/harem/Harem.ts
src/Service/AutoLoop.ts
src/Service/ParanoiaService.ts
src/config/game/MangaRpgVars.ts

Fix loop on paranoia switch
other fixes
Club Champion in MangaRPG #1320

Fix enabling pop #1317

---

HHAuto.user.js
package.json
src/Helper/HHMenuHelper.ts
src/Module/Events/EventModule.ts
src/Module/Events/PathOfAttraction.ts
src/Module/Missions.ts
src/config/HHStoredVars.ts
src/i18n/en.ts
src/model/Mission.ts

Add option to start with longer mission #1322

---

HHAuto.user.js
build/HHAuto.template.js
package.json
src/Helper/HHMenuHelper.ts
src/Module/DailyGoals.ts
src/Module/GenericBattle.ts
src/Module/Pantheon.ts
src/Service/AutoLoop.ts
src/Service/InfoService.ts
src/Service/StartService.ts
src/config/HHEnvVariables.ts
src/config/HHStoredVars.ts
src/config/game/HentaiHeroesVars.ts
src/config/game/PornstarHaremVars.ts
src/i18n/en.ts
src/index.ts
src/model/KK/index.ts
src/model/KK/kkDailyGoal.ts

Prepare update for auto daily goal feature (not working yet)

Add new troll and new world

---

HHAuto.user.js
package.json
src/Helper/HHMenuHelper.ts
src/Module/Labyrinth.ts
src/config/HHStoredVars.ts
src/i18n/en.ts

Auto laby harder mode #1126

---

HHAuto.user.js
package.json
src/Helper/RewardHelper.ts
src/Module/GenericBattle.ts
src/Module/Troll.ts
src/Service/StartService.ts

Fix event girl reward detection

---

HHAuto.user.js
package.json
src/Module/Labyrinth.ts
src/Module/LabyrinthAuto.ts

Auto select laby difficulty if only one available

Update laby algorithm #1126
